### ISSUE TITLE
hi i am prabhav i want to submit my code here

### ISSUE THREAD

**Issue by prolad** [Nested-Amigos/zoom-automation-bot#1]

**Comment by Sahil2004** [comment]
Okay. So, you can submit you code. Just fork this and then submit a PR. I am assigning this to you. Please don't change a lot of it. First see how github works and how PR's are submitted.And don't just dump your code. First read what code is already done. See where you can make changes. Then tell us what you would like to change and then start changing it. **Please do not dump your code here.** No one is free enough to integrate it into the code base. And also it might happen that whatever you have already done is also done here. So just see what is already done, check if you can make it better, submit a PR accordingly.
